# Generated by Django 3.2.8 on 2021-11-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilPerusahaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(default='Unknown company name', max_length=50)),
                ('companyAddress', models.TextField(default='Unknown Address')),
                ('companyEmail', models.EmailField(default='Unknown Email', max_length=254)),
                ('companyPhoneNumber', models.CharField(default='Unknown Phone Number', max_length=13)),
                ('companyDescription', models.TextField(default='Unknown Company Description')),
                ('companyOwner', models.CharField(default='UnknownOwner', max_length=30)),
            ],
        ),
    ]
