# Generated by Django 3.2.8 on 2021-10-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilperusahaan', '0002_remove_profilperusahaan_companyowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilperusahaan',
            name='companyOwner',
            field=models.CharField(default='admin', max_length=30),
            preserve_default=False,
        ),
    ]
