# Generated by Django 3.2.8 on 2021-11-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=150)),
                ('message', models.TextField()),
                ('postTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
