# Generated by Django 3.2.8 on 2021-10-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_postforum_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postforum',
            name='message',
            field=models.TextField(max_length=1200),
        ),
    ]
