# Generated by Django 3.2.8 on 2021-10-21 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0003_alter_postforum_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postforum',
            name='author',
            field=models.ForeignKey(default='John Doe', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
