# Generated by Django 3.2.8 on 2021-10-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_postforum_asparent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postforum',
            name='asParent',
        ),
    ]
