# Generated by Django 3.2.8 on 2021-10-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_postforum_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postforum',
            name='author',
        ),
    ]
