# Generated by Django 3.2.8 on 2021-10-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_remove_postforum_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postforum',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='postforum',
            name='postTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postforum',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
