# Generated by Django 3.2.8 on 2021-10-21 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20211022_0350'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostForum',
        ),
    ]
