# Generated by Django 3.2.8 on 2021-10-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_postforum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postforum',
            name='postTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
