# Generated by Django 3.2.8 on 2021-10-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_alter_postforum_posttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postforum',
            name='author',
        ),
        migrations.AlterField(
            model_name='postforum',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='postforum',
            name='postTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='postforum',
            name='title',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
