# Generated by Django 3.2.7 on 2021-10-24 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_alter_postforum_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postforum',
            name='author',
        ),
    ]
