# Generated by Django 3.2.8 on 2021-11-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LowonganKerja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobs', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('jobType', models.CharField(max_length=10)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pelamar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('usia', models.IntegerField()),
                ('pendidikan', models.CharField(max_length=20)),
                ('alamat', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('jenisKelamin', models.CharField(max_length=10)),
                ('sertifikatVaksin', models.TextField()),
                ('idLowongan', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
