# Generated by Django 3.2.8 on 2021-10-22 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pelamar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pelamar',
        ),
    ]
