# Generated by Django 3.2.8 on 2021-10-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_pelamar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelamar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('usia', models.IntegerField()),
                ('pendidikan', models.CharField(max_length=20)),
                ('alamat', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('jenisKelamin', models.CharField(max_length=10)),
                ('sertifikatVaksin', models.FileField(upload_to='')),
                ('jobs', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
            ],
        ),
    ]
