# Generated by Django 3.2.8 on 2021-10-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pelamar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelamar',
            name='idLowongan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
