# Generated by Django 3.2.7 on 2021-10-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_lowongankerja_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelamar',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
