# Generated by Django 3.2.8 on 2021-11-04 06:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipskarier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Article', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Cover', models.ImageField(blank=True, null=True, upload_to='static/images/tipskarier/')),
                ('Summary', models.TextField(max_length=500, null=True)),
                ('Highlight', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
