# Generated by Django 3.2.8 on 2021-10-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipskarier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipskarier',
            name='Summary',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
