# Generated by Django 3.2.8 on 2021-10-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipskarier', '0002_tipskarier_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipskarier',
            name='Article',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipskarier',
            name='Cover',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/tipskarier/'),
        ),
    ]
