# Generated by Django 3.2.8 on 2021-10-30 13:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipskarier', '0003_auto_20211029_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipskarier',
            name='Article',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
