# Generated by Django 3.2.8 on 2021-11-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipskarier', '0004_alter_tipskarier_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipskarier',
            name='Highlight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
