# Generated by Django 3.2.8 on 2021-11-03 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
        ('company_review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pekerjaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perusahaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lowongankerja')),
            ],
        ),
        migrations.AddField(
            model_name='company_review',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='perusahaanKomen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pekerjaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_review.pekerjaan')),
                ('penulis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
