# Generated by Django 3.2.8 on 2021-11-04 11:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company_review', '0002_auto_20211103_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_review',
            name='name',
        ),
        migrations.AlterUniqueTogether(
            name='perusahaankomen',
            unique_together={('pekerjaan', 'penulis')},
        ),
    ]
