# Generated by Django 3.2.8 on 2021-11-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_review', '0003_auto_20211104_1815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='company_review',
        ),
        migrations.AddField(
            model_name='perusahaankomen',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='perusahaankomen',
            name='postTime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='perusahaankomen',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
