# Generated by Django 3.2.8 on 2021-11-04 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('company_review', '0004_auto_20211104_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perusahaankomen',
            name='pekerjaan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lowongankerja'),
        ),
        migrations.DeleteModel(
            name='pekerjaan',
        ),
    ]
